Repository 33-1-3/33-1-3-server, pull requests merged in 2022-12, with the labels that each got.

#2 데이터 Schema 구현
  index.js
  models/Auth.js
  models/Collection.js
  models/CommonVinyl.js
  models/UserVinyl.js
  models/index.js
  package-lock.json
  package.json
Labels: Backend, Implement

#3 초기 파일 구조 완성
  index.js
Labels: Backend, Implement

#5 컬렉션 CRUD 구현
  index.js
  models/Collection.js
Labels: Backend, Implement

#7 FEAT: DB CRUD 함수 작성
  index.js
  models/UserVinyl.js
Labels: Backend, Implement

#8 회원가입, 로그인 CRUD 로직 구현
  index.js
  models/Collection.js
Labels: Backend, Implement

#11 api 응답 데이터 수정 및 cors 추가
  index.js
Labels: Bug, Backend

#13 이메일 인증 구현 및 로그인, 회원가입 에러 처리를 위한 응답 변경
  index.js
  models/Auth.js
  package-lock.json
  package.json
  verification/emailTemplate.ejs
Labels: Config, Backend, Implement

#18 database에 저장되는 사용자 비밀번호 암호화
  index.js
  package-lock.json
  package.json
Labels: Backend, Implement

#21 린트 및 htmlhint 오류 관련 설정 추가
  .eslintignore
  .eslintrc.js
  .prettierignore
  .vscode/settings.json
  index.js
  verification/emailTemplate.ejs
Labels: Config, Enhancement

#23 Collection 렌더링 요청의 응답 로직 변경
  index.js
  models/Collection.js
Labels: Bug, Backend

#27 Add Item 모달 이벤트 처리
  .eslintignore
  .eslintrc.js
  .prettierignore
  .vscode/settings.json
  index.js
  models/Auth.js
  models/Collection.js
  models/CommonVinyl.js
  models/UserVinyl.js
  models/index.js
  package-lock.json
  package.json
  verification/emailTemplate.ejs
Labels: Backend

#29 Add Item 모달 이벤트 처리
  index.js
Labels: Backend

#31 CORS 설정 추가
  index.js
Labels: Backend, Implement

#32 FIX: CORS 에러 해결
  index.js
Labels: Bug, Backend

#33 콜렉션 목록 최신순 정렬
  index.js
Labels: Backend, Implement
